name: Trigger Web App
 
on:
  push:
    branches: [ "main" ]
 
jobs:
  call-webapp:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger other repo
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
https://github.com/aiwaken-ltd/web-application/blob/main/.github/workflows/listener.yml/dispatches \
          -d '{"ref":"main"}'
